language: generic
sudo: required
service:
  - docker

before_install:
  - docker build -t parisk85/udemy-multi-docker-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true parisk85/udemy-multi-docker-react-test npm test -- --coverage

after_success:
  - docker build -t parisk85/udemy-multi-docker-client ./client
  - docker build -t parisk85/udemy-multi-docker-nginx ./nginx
  - docker build -t parisk85/udemy-multi-docker-server ./server
  - docker build -t parisk85/udemy-multi-docker-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to DockerHub
  - docker push parisk85/udemy-multi-docker-client
  - docker push parisk85/udemy-multi-docker-nginx
  - docker push parisk85/udemy-multi-docker-server
  - docker push parisk85/udemy-multi-docker-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "udemy-multi-docker"
  env: "UdemyMultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-670338847205"
  bucket_path: "udemy-multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY